name: test

on:
  pull_request:
  push:
    branches: [ main ]

permissions:
  contents: read

jobs:
  rust-test:
    name: Unit tests (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Rust (1.89.0)
        uses: dtolnay/rust-toolchain@1.89.0
        with:
          # toolchain は rust-toolchain.toml に準拠
          components: rustfmt, clippy

      - name: Install Linux dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libxcb1-dev \
            libxcb-render0-dev \
            libxcb-shape0-dev \
            libxcb-xfixes0-dev

      - name: Cache cargo
        uses: Swatinem/rust-cache@v2

      - name: Build
        run: cargo build --all --verbose

      - name: Test
        run: cargo test --all --verbose

